title = "boxdox's blog"
baseURL = "https://boxdox.dev"
languageCode = "en-us"
disableHugoGeneratorInject = true

[params]
    author = "boxdox"
    description = "personal space for showcasing work of @boxdox"
    themeColor = "#ed5072"
    ogimage = "/images/og.jpg"

[markup]
  [markup.highlight]
    codeFences = true
    style = "dracula"
    tabWidth = 2

[taxonomies]
  tag = "tags"
