baseURL = "https://boxdox.dev"
disableHugoGeneratorInject = true
languageCode = "en-us"
title = "boxdox's blog"

[params]
author = "boxdox"
description = "personal space for showcasing work of @boxdox"
ogimage = "/images/og.jpg"
themeColor = "#ed5072"

[markup]
[markup.highlight]
codeFences = true
style = "dracula"
tabWidth = 2

[taxonomies]
tag = "tags"
