[[headers]]
for = "/*"
[headers.values]
cache-control = 'public, max-age=604800, immutable'

[[redirects]]
from = '/*'
status = 404
to = '/404.html'

[build]
command = "yarn install && hugo --gc"
publish = "public"

[context.production.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.81.0"
