backend:
  name: git-gateway
  branch: main
  squash_merges: true

site_url: https://boxdox.dev
display_url: https://boxdox.dev
media_folder: static/img
show_preview_links: true

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'home'
        label: 'Home'
        file: 'content/_index.md'
        fields:
          - { label: 'Body', name: 'body', widget: 'markdown' }

      - name: 'about'
        label: 'About'
        file: 'content/about.html'
        extension: 'html'
        fields:
          - { label: 'Body', name: 'body', widget: 'text' }

  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    path: '{{slug}}/index'
    preview_path: 'blog/{{slug}}'
    extension: 'md'
    format: yaml-frontmatter
    media_folder: ''
    public_folder: ''
    create: true
    slug: '{{slug}}'

    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Cover', name: 'cover', widget: 'image', required: false }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
      - { label: 'Language', name: 'language', widget: 'hidden', default: 'en' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'til'
    label: 'TIL'
    folder: 'content/til'
    path: '{{slug}}/index'
    extension: 'md'
    preview_path: 'til/{{slug}}'
    media_folder: ''
    public_folder: ''
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
      - { label: 'Language', name: 'language', widget: 'hidden', default: 'en' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
